#!/bin/sh

set -ex

echo building
# git describe --always --tags --dirty --long)
REVISION=`git rev-parse --short=5  HEAD`
BUILDTIME=`TZ=UTC date "+%Y-%m-%dT%H:%MZ"`
echo $REVISION > REVISION

OS=${GOOS:-`go env GOOS`}
ARCH=${GOARCH:-`go env GOARCH`}

set -ex

go build -o dist/geodns-$OS-$ARCH \
  -ldflags "-X main.gitVersion=$REVISION -X main.buildTime=$BUILDTIME" \
  -v && \
  (cd geodns-influxdb && go build -v -o ../dist/geodns-influxdb-$OS-$ARCH && cd ..) && \
cd dist && \
tar -cvHf geodns-$OS-$ARCH.tar \
 --exclude \*~ geodns-$OS-$ARCH \
 geodns-influxdb-$OS-$ARCH service service-influxdb
