#!/bin/sh
exec 2>&1
sleep 1 # just in case we spin for some reason

cd /opt/geodns

INTERFACE=""
if [ -e env/IP ]; then
  IP=`head -1 env/IP`
  if [ ! -z "$IP" ]; then
    INTERFACE="--interface=$IP"
  fi
fi

ID=""
if [ -e env/ID ]; then
  ID=`head -1 env/ID`
  if [ ! -z "$ID" ]; then
      ID="--identifier=$ID"
  fi
fi


CONFIG=dns
if [ -e env/CONFIG ]; then
  CONFIG=`head -1 env/CONFIG`
fi

ulimit -n 64000

exec softlimit -d500000000 ./geodns $INTERFACE $ID --config="$CONFIG"
