#!/bin/bash

set -euo pipefail

go install github.com/goreleaser/goreleaser@v1.22.1

DRONE_TAG=${DRONE_TAG-""}

is_snapshot=""

if [ -z "$DRONE_TAG" ]; then
  is_snapshot="--snapshot"
fi

goreleaser release $is_snapshot -p 6 --skip=publish
